#!/bin/bash
if [[ -z "$SCONTROL" ]] ; then
	SCONTROL="Capture"
fi

if [[ -z "$STEP" ]] ; then
    STEP="${1:-5%}"
fi

#------------------------------------------------------------------------
case $BLOCK_BUTTON in
  1) pavucontrol ;; # left click
  3) amixer -q sset $SCONTROL toggle ;;  # right click, mute/unmute
  4) amixer -q sset $SCONTROL ${STEP}+ unmute ;; # scroll up, increase
  5) amixer -q sset $SCONTROL ${STEP}- unmute ;; # scroll down, decrease
esac

status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  echo "🎙  ${volume}%"
  echo "🎙  ${volume}%"
  if [[ "${volume}" == "0" ]]; then
  	echo \#ffff00
  else
	  echo \#ffffff
	fi
else
  echo "🎙  off"
  echo "🎙  off"
  echo \#ff0000
fi
