theme = "zenburn"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.whitespace]
render = "all"

[editor.statusline]
left = ["mode", "spinner", "file-name", "version-control"]

[editor.indent-guides]
character = "╎"
render = true

[keys.insert]
C-b = "move_char_left"
C-f = "move_char_right"

A-b = "move_prev_word_start"
A-f = "move_next_word_start"

C-a = "goto_line_start"
C-e = "goto_line_end_newline"

C-p = "move_line_up"
C-n = "move_line_down"

C-space = "select_mode"

[keys.select]
C-space = "insert_mode"
